<a href="https://colab.research.google.com/github/fi0909/Desain-dan-Analisis-Algoritma/blob/main/Pertemuan3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
listku =["John", "Toronto", True]
print (listku)

['John', 'Toronto', True]


In [22]:
import datetime
from datetime import datetime
x = datetime.now()
hari = str(x)
Mahasiswa = ["Muhammad Luthfi Taufikurrahman", "2022071053" ,"Informatika", "Desain dan Analisis Algoritma ", hari, "Universitas Pembangunan jaya"]
print(Mahasiswa)

['Muhammad Luthfi Taufikurrahman', '2022071053', 'Informatika', 'Desain dan Analisis Algoritma ', '2023-09-11 06:32:00.329539', 'Universitas Pembangunan jaya']


In [28]:
Lwarna = ('red','green','blue','yellow')
Lwarna[1]

'green'

In [25]:
Mahasiswa[1]

'2022071053'

In [26]:
Mahasiswa[5]

'Universitas Pembangunan jaya'

In [40]:
Lwarna[0:6]

('red', 'green')

In [57]:
Mahasiswa = ["Muhammad Luthfi Taufikurrahman", "2022071053" ,"Informatika", "Desain dan Analisis Algoritma ", hari, "Universitas Pembangunan jaya"]
Mahasiswa[3:4]

['Desain dan Analisis Algoritma ']

In [34]:
for item in Lwarna:
  print(item + "Square")

redSquare
greenSquare
blueSquare
yellowSquare


In [38]:
for item in Mahasiswa:
  print("UPJ "+ item)

UPJ Muhammad Luthfi Taufikurrahman
UPJ 2022071053
UPJ Informatika
UPJ Desain dan Analisis Algoritma 
UPJ 2023-09-11 06:32:00.329539
UPJ Universitas Pembangunan jaya


In [39]:
Lwarna[1]
Lwarna[2:]

('blue', 'yellow')

In [42]:
UPJ = ("Universitas", "Pembangunan", "Jaya")
print(UPJ)

('Universitas', 'Pembangunan', 'Jaya')


In [43]:
hariawal = ("senin","selasa","rabu")
hariakhir = ("kamis","jumat","sabtu")
hari = (hariawal,hariakhir)
print(hari)

(('senin', 'selasa', 'rabu'), ('kamis', 'jumat', 'sabtu'))


In [44]:
pertama = ('100')
kedua = ('200','400','600')
ketiga = ('300')
keempat = ('400','800')
nested_tuple = (pertama,kedua,ketiga,keempat)
print(nested_tuple)

('100', ('200', '400', '600'), '300', ('400', '800'))


In [45]:
Lwarna ={
    "manual_color":"yellow",
    "approved_color":"Green",
    "refused_color":"red"
}
print(Lwarna)

{'manual_color': 'yellow', 'approved_color': 'Green', 'refused_color': 'red'}


In [47]:
Lwarna.get('approved_color')
Lwarna['approved_color']

'Green'

In [48]:
Lwarna['approved_color']="purple"
print(Lwarna)

{'manual_color': 'yellow', 'approved_color': 'purple', 'refused_color': 'red'}


In [55]:
Mahasiswa ={
    "nama":"Muhammad Luthfi Taufikurrahman",
    "NIM":"2022071053",
    "Prodi": "Informatika",
    "Universitas":"UPJ"
}
print(Mahasiswa)

{'nama': 'Muhammad Luthfi Taufikurrahman', 'NIM': '2022071053', 'Prodi': 'Informatika', 'Universitas': 'UPJ'}


In [ ]:
acak= (True ,{'name': 'depotkode','status':'alive'},[1,2,3])

In [58]:
green = {'grass','leaves'}
print(green)

{'leaves', 'grass'}


In [59]:
green = {'grass', 'leaves','leaves'}
print(green)

('grass', 'leaves', 'leaves')


In [60]:
set1={4,5,6,2}
print(set1)

{2, 4, 5, 6}


In [61]:
set2 = set()
set3 = set([2,1,4,3])
print(type(set2))
print(set3)

<class 'set'>
{1, 2, 3, 4}


In [62]:
set4 = {2,3,4,5,6}
set4.add(1)
print(set4)

{1, 2, 3, 4, 5, 6}


In [63]:
set4 = {1,2,3,4,5,6,7,8}
set4.discard(4)
print(set4)

{1, 2, 3, 5, 6, 7, 8}


In [64]:
set4.add(10)
print(set4)

{1, 2, 3, 5, 6, 7, 8, 10}


In [65]:
seta={1,2,3,4}
setb={3,4,5,6}
print(seta|setb)
print(seta.union(setb))

{1, 2, 3, 4, 5, 6}
{1, 2, 3, 4, 5, 6}


In [66]:
print(seta&setb)
print(seta.intersection(setb))

{3, 4}
{3, 4}


In [67]:
print(seta-setb)
print(seta.difference(setb))

{1, 2}
{1, 2}


In [68]:
print(setb-seta)
print(setb.difference(seta))

{5, 6}
{5, 6}


In [69]:
print(seta^setb)
print(seta.symmetric_difference(setb))

{1, 2, 5, 6}
{1, 2, 5, 6}


In [71]:
yellow = {'dandelions','fire hydrant','leaves'}
red = {'leaves', 'fire hydrant','rose','blood'}
print(yellow|red)
print(yellow&red)

{'rose', 'blood', 'fire hydrant', 'leaves', 'dandelions'}
{'leaves', 'fire hydrant'}


In [74]:
import pandas as pd
df = pd.DataFrame([
    ['1','fares',32,True],
    ['2','elena',23,False],
    ['3','steven', 40 , True]
])
df.columns = ['id','name','age','decision']
print(df)

  id    name  age  decision
0  1   fares   32      True
1  2   elena   23     False
2  3  steven   40      True


In [103]:
import pandas as pd
data= {
    "name" : ["fares","elena","steven"],
    "age" : [22, 23, 40]
}
df=pd.DataFrame(data)
df.iloc[1:3]
print(df)
print(df.iloc[0:3])

     name  age
0   fares   22
1   elena   23
2  steven   40
     name  age
0   fares   22
1   elena   23
2  steven   40


In [105]:
import pandas as pd

data={
    "no":[1,2,3],
    "prodi": ["informatika","Sistem informasi","Teknik Sipil"],
    "Mahasiswa": [50 ,55 ,40],
    "lakilaki": [30,30,30],
    "Perembuan" : [20,25,10]
}
df = pd.DataFrame(data, index = ['-','-','-'])
print(df)

   no             prodi  Mahasiswa  lakilaki  Perembuan
-   1       informatika         50        30         20
-   2  Sistem informasi         55        30         25
-   3      Teknik Sipil         40        30         10


In [108]:
import numpy as np
matriksa=np.array([[100,200,300],[700,600,500],[900,1000,800]])
transposea= np.transpose(matriksa)
print("matriks a : ")
print(matriksa)
print("tranpose : ")
print(transposea)


matriks a : 
[[ 100  200  300]
 [ 700  600  500]
 [ 900 1000  800]]
tranpose : 
[[ 100  700  900]
 [ 200  600 1000]
 [ 300  500  800]]


In [ ]:
Vectorku=[22,33,44,55]
print(Vectorku)
print(type(Vectorku))

In [114]:
class Stack:
  def __init__(self):
    self.items = []
  def isEmpty(self):
    return self.items == []
  def push(self, item):
    self.items.append(item)
  def pop (self):
    return self.items.pop()
  def peek(self):
    return self.items.pop()
  def peek(self):
    return self.items[len(self.items)-1]
  def size(self):
    return len(self.items)

stack = Stack()
stack.push('red')
stack.push('green')
stack.push("blue")
stack.push("yellow")

stack.pop()
stack.isEmpty()

False

perbedan tuple dengan sets
tuple = elemen didalamnya bisa di copy kembali()
sets = elemennya tidak bisa di copy {}
Union = |